# Настройки для users

USERNAME_MAX_LENGTH = 150
ALLOWED_SYMBOLS_FOR_LOGIN = r'[\w.@+-]'
WORD_SELF_USER_URL = 'me'
INVALID_WORDS_FOR_LOGIN = (WORD_SELF_USER_URL,)

FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

EMAIL_MAX_LENGTH = 254

# PASSWORD_MAX_LENGTH = 100

DEFAULT_FROM_EMAIL = 'admiral@foodgram.ru'
