# Generated by Django 3.2.3 on 2023-09-19 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='id_username',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='id_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
