# Generated by Django 3.2.3 on 2023-10-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231010_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-id_writer'], 'verbose_name': 'Подписка на автора', 'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
