# Generated by Django 3.2.3 on 2023-09-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230930_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Подписка на автора', 'verbose_name_plural': 'Подписки на авторов'},
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='id_subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_subscriber', to='users.users', verbose_name='Кто подписался'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='id_writer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_writer', to='users.users', verbose_name='На кого подписан'),
            preserve_default=False,
        ),
    ]
