# Generated by Django 3.2.3 on 2023-10-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231001_1026'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='unique_id_subscriber_id_writer',
        ),
    ]
