# Generated by Django 3.2.3 on 2023-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_subscriptions_unique_id_subscriber_id_writer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('id_subscriber', 'id_writer'), name='unique_id_subscriber_id_writer'),
        ),
    ]
