# Generated by Django 3.2.3 on 2023-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscriptions_unique_id_subscriber_id_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_favorited',
            field=models.BooleanField(default=False, verbose_name='Избраное'),
        ),
    ]
