# Generated by Django 3.2.3 on 2023-10-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_users_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_favorited',
        ),
    ]
