# Generated by Django 3.2.3 on 2023-10-10 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recipes.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ингридиента')),
                ('measurement_unit', models.CharField(max_length=200, verbose_name='Измерения ингридиента')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество.')),
                ('id_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_connection_r', to='recipes.ingredients', verbose_name='Индификатор ингридиента.')),
            ],
            options={
                'verbose_name': 'Рицепт < Ингридиент.',
                'verbose_name_plural': 'Рицепты < Ингридиенты.',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рицепта.')),
                ('image', models.ImageField(default=None, null=True, upload_to=recipes.utils.get_file_path, verbose_name='Картинка рицепта.')),
                ('text', models.TextField(default='', verbose_name='Описание')),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки в минутах.')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации.')),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='author_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор рицепта.')),
                ('ingredients', models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.Ingredients', verbose_name='Ингридиенты.')),
            ],
            options={
                'verbose_name': 'Рицепт',
                'verbose_name_plural': 'Рицепты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сортировки')),
                ('color', models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{6})', message='Формат для HEX.')], verbose_name='Цвет в RGB')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Текс цвета выделения')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TagsRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tr_recept', to='recipes.recipes', verbose_name='Индификатор рицепта')),
                ('id_teg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tr_teg', to='recipes.tags', verbose_name='Индификатор тега')),
            ],
            options={
                'verbose_name': 'Рицепт < Тег.',
                'verbose_name_plural': 'Рицепты < Теги.',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_recipe', to='recipes.recipes', verbose_name='Рицепт в корзине.')),
                ('id_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в корзину.')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(through='recipes.TagsRecipes', to='recipes.Tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_connection_i', to='recipes.recipes', verbose_name='Индификатор рицепта.'),
        ),
        migrations.CreateModel(
            name='Favorited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe', to='recipes.recipes', verbose_name='Избраный рицепт.')),
                ('id_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в избранное.')),
            ],
            options={
                'verbose_name': 'Избраный',
                'verbose_name_plural': 'Избраные',
            },
        ),
    ]
