# Generated by Django 3.2.3 on 2023-09-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сортировки')),
                ('color', models.CharField(max_length=16, verbose_name='Цвет выделения')),
                ('slug', models.SlugField(unique=True, verbose_name='Цвет в RGB')),
            ],
        ),
    ]
