# flake8: noqa
# Generated by Django 3.2.3 on 2023-10-12 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorited',
            options={'ordering': ['id_user'], 'verbose_name': 'Избраный', 'verbose_name_plural': 'Избраные'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name'], 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ['id_ingredient'], 'verbose_name': 'Рицепт < Ингридиент.', 'verbose_name_plural': 'Рицепты < Ингридиенты.'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['id_user'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-slug'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagsrecipes',
            options={'ordering': ['id_teg'], 'verbose_name': 'Рицепт < Тег.', 'verbose_name_plural': 'Рицепты < Теги.'},
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Количество.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Время готовки в минутах.'),
        ),
    ]
