# Generated by Django 3.2.3 on 2023-09-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230919_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='id_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_ri_ingredient', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='id_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_ri_recept', to='recipes.recipes'),
        ),
    ]
