# flake8: noqa
# Generated by Django 3.2.3 on 2023-10-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ing', through='recipes.RecipeIngredients', to='recipes.Ingredients', verbose_name='Ингридиенты.'),
        ),
    ]
