# Generated by Django 3.2.3 on 2023-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_favorited_shoppinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
