# Generated by Django 3.2.3 on 2023-09-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230922_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='name_ingredient',
            new_name='name',
        ),
    ]
