# Generated by Django 3.2.3 on 2023-09-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_name_ingredient_ingredients_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='id_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='name_recipe',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет в RGB'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Текс цвета выделения'),
        ),
    ]
