# Generated by Django 3.2.3 on 2023-09-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230926_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='name',
        ),
        migrations.AddField(
            model_name='recipes',
            name='name_recipe',
            field=models.CharField(default=0, max_length=200, verbose_name='Название рицепта'),
            preserve_default=False,
        ),
    ]
