# Generated by Django 3.2.3 on 2023-09-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230926_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='name_recipe',
            new_name='name',
        ),
    ]
