# Generated by Django 3.2.3 on 2023-09-30 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_auto_20230927_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Связь (рицептом < ингридиентами).', 'verbose_name_plural': 'Связи (рицептом < ингридиентами).'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рицепт', 'verbose_name_plural': 'Рицепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterField(
            model_name='favorited',
            name='id_recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe_id', to='recipes.recipes', verbose_name='Избраный рицепт.'),
        ),
        migrations.AlterField(
            model_name='favorited',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в избранное.'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество.'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='id_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_connection_r', to='recipes.ingredients', verbose_name='Индификатор ингридиента.'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_connection_i', to='recipes.recipes', verbose_name='Индификатор рицепта.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_author_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рицепта.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки в минутах.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/', verbose_name='Картинка рицепта.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.Ingredients', verbose_name='Ингридиенты.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название рицепта.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации.'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(through='recipes.TagsRecipes', to='recipes.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id_recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_recipe_id', to='recipes.recipes', verbose_name='Рицепт в корзине.'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в корзину.'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{6})', message='Формат для HEX.')], verbose_name='Цвет в RGB'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Текс цвета выделения'),
        ),
        migrations.AlterField(
            model_name='tagsrecipes',
            name='id_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tr_recept', to='recipes.recipes', verbose_name='Индификатор рицепта'),
        ),
        migrations.AlterField(
            model_name='tagsrecipes',
            name='id_teg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tr_teg', to='recipes.tags', verbose_name='Индификатор тега'),
        ),
    ]
