# Generated by Django 3.2.3 on 2023-09-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230930_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorited',
            options={'verbose_name': 'Избраный', 'verbose_name_plural': 'Избраные'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Рицепт < Ингридиент.', 'verbose_name_plural': 'Рицепты < Ингридиенты.'},
        ),
        migrations.AlterModelOptions(
            name='tagsrecipes',
            options={'verbose_name': 'Рицепт < Тег.', 'verbose_name_plural': 'Рицепты < Теги.'},
        ),
    ]
