# Generated by Django 3.2.3 on 2023-10-04 08:29

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=recipes.utils.get_file_path, verbose_name='Картинка рицепта.'),
        ),
    ]
