# Generated by Django 3.2.3 on 2023-10-08 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0018_auto_20231007_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorited',
            name='id_recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipe', to='recipes.recipes', verbose_name='Избраный рицепт.'),
        ),
        migrations.AlterField(
            model_name='favorited',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в избранное.'),
        ),
    ]
