# Generated by Django 3.2.3 on 2023-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20231008_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_favorited',
            field=models.BooleanField(default=False, verbose_name='Избраное'),
        ),
    ]
