# Generated by Django 3.2.3 on 2023-10-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_recipes_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='is_favorited',
        ),
    ]
