# Generated by Django 3.2.3 on 2023-10-08 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0021_remove_recipes_is_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='id_recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_recipe', to='recipes.recipes', verbose_name='Рицепт в корзине.'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в корзину.'),
        ),
    ]
