# Generated by Django 3.2.3 on 2023-10-08 12:04

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20231008_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=recipes.utils.get_file_path, verbose_name='Картинка рицепта.'),
        ),
    ]
